application:
  title: @project.name@
  version: @project.version@
spring:
  application:
    name: wallet-app
  jackson:
    time-zone: UTC
    deserialization:
      adjust-dates-to-context-time-zone: true
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:walletDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;'
    username: sa
    password: ''
  liquibase:
    enabled: true
    change-log: 'db/changelog/db.changelog-master.xml'
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
